/**
 * Registration Data Models
 *
 * Defines all interfaces and types used for user registration
 * - AuthUserData: Data stored in auth_user database table
 * - UserInformation: Data stored in user_information database table
 * - RegistrationFormData: Data from the registration form (frontend)
 */

// ═════════════════════════════════════════════════════════════════════════
// AUTH USER DATABASE MODEL
// ═════════════════════════════════════════════════════════════════════════

/**
 * AuthUserData - Core authentication user record
 * Stored in: auth_user database table
 *
 * These are the essential fields for authentication and user identification.
 * Used by: AuthUserService for saving/updating user authentication info.
 *
 * Purpose: Secure storage of credentials and authentication metadata
 */
export interface AuthUserData {
  // System Fields
  id?: number;
  // Primary key in auth_user table
  // Auto-generated by database
  // Example: 1, 2, 3, etc.

  referenceNumber: string;
  // Unique reference identifier for user
  // Format: AUTH-{timestamp}-{random}
  // Example: AUTH-07951234-5678
  // Purpose: Business-friendly unique ID separate from database ID

  // Credential Fields
  email: string;
  // User's email address (unique)
  // Example: "john.doe@example.com"
  // Used for: Login, password recovery, contact

  password?: string;
  // Hashed password (backend hashes this, frontend sends plain text)
  // Note: Frontend should never store plain passwords
  // Note: Backend receives plain, hashes, and stores hashed version

  // Identity Fields
  firstName: string;
  // User's first name
  // Example: "John"

  lastName: string;
  // User's last name / surname
  // Example: "Doe"

  // Access Control
  role: 'PATIENT' | 'DOCTOR' | 'ADMIN';
  // User type determining permissions and features
  // PATIENT: Patient user account
  // DOCTOR: Healthcare provider account
  // ADMIN: System administrator account

  // Contact Fields
  mobilePhone: string;
  // Full phone number with country code
  // Format: {countryCode}{number}
  // Example: "+263712345678" or "+11234567890"

  // Audit Fields (backend sets these)
  createdAt?: string;
  // Timestamp when record was created
  // Format: ISO 8601 (e.g., "2026-03-02T23:34:00Z")

  updatedAt?: string;
  // Timestamp when record was last updated
  // Format: ISO 8601
}

// ═════════════════════════════════════════════════════════════════════════
// USER INFORMATION DATABASE MODEL
// ═════════════════════════════════════════════════════════════════════════

/**
 * UserInformation - Extended user profile
 * Stored in: user_information database table
 *
 * Extended profile information beyond core authentication.
 * Linked to auth_user via: referenceNumber
 * Used by: UserInformationService for saving/updating profile data.
 *
 * Purpose: Complete user profile including personal, health, and document info
 */
export interface UserInformation {
  // System Fields
  id?: number;
  // Primary key in user_information table
  // Auto-generated by database

  referenceNumber: string;
  // Foreign key linking to auth_user.referenceNumber
  // Purpose: Link profile to auth record without relying on database IDs
  // Example: "AUTH-07951234-5678" (same as in auth_user)

  // Personal Information
  dateOfBirth?: string;
  // Date of birth
  // Format: YYYY-MM-DD (e.g., "1990-05-15")
  // Used for: Age calculation, age-appropriate features

  gender?: 'Male' | 'Female' | 'Other';
  // User's gender
  // Used for: Medical history, health recommendations

  // Location Information
  country?: string;
  // Country of residence
  // Example: "Zimbabwe", "United States", "United Kingdom"

  city?: string;
  // City of residence
  // Example: "Harare", "New York", "London"

  streetAddress?: string;
  // Street address
  // Example: "123 Main Street"

  state?: string;
  // State/Province
  // Example: "California", "New York"

  zipCode?: string;
  // Postal code/ZIP code
  // Example: "10001", "90210"

  // Identity Document Information
  nationalIdNumber?: string;
  // National ID number (if user chose this document type)
  // Example: "ZW123456789"
  // Optional: Only present if documentType is 'nationalId'

  passportNumber?: string;
  // Passport number (if user chose this document type)
  // Example: "A12345678"
  // Optional: Only present if documentType is 'passport'

  // File Storage
  profilePictureUrl?: string;
  // URL/path to user's profile picture
  // Stored in: Cloud storage or local file system
  // Example: "/uploads/profile-pictures/user-1-photo.jpg"

  supportingDocuments?: string[];
  // Array of URLs/paths to supporting documents
  // Stored in: Cloud storage or local file system
  // Example: ["/uploads/documents/user-1-doc1.pdf", "/uploads/documents/user-1-doc2.pdf"]

  // Audit Fields (backend sets these)
  createdAt?: string;
  // Timestamp when record was created
  // Format: ISO 8601

  updatedAt?: string;
  // Timestamp when record was last updated
  // Format: ISO 8601
}

// ═════════════════════════════════════════════════════════════════════════
// REGISTRATION FORM DATA MODEL
// ═════════════════════════════════════════════════════════════════════════

/**
 * RegistrationFormData - Frontend form input
 * Source: register.component.ts form data
 *
 * This is the raw data collected from the registration form.
 * It combines fields from both auth_user and user_information tables.
 * Used by: RegistrationHandlerService to split and route data.
 *
 * Note: This is a convenience model that includes all form fields.
 * The service will split this into AuthUserData and UserInformation.
 */
export interface RegistrationFormData {
  // Generated Fields
  referenceNumber?: string;
  // Auto-generated by orchestrator during registration
  // Format: INITIALS + ROLE_PREFIX + DATE(DDMMYY) + RANDOM_3_DIGIT + TIME(12hr)
  // Example: "JEPA130326456-1430"
  // Note: Component passes undefined; orchestrator generates and enriches it

  // Auth Fields (go to auth_user table)
  firstName: string;
  surname: string; // becomes lastName in AuthUserData
  email: string;
  password: string;
  role: 'PATIENT' | 'DOCTOR' | 'ADMIN';
  phoneCountryCode: string; // e.g., "+263"
  phoneNumber: string; // e.g., "712345678"
  // Combined into mobilePhone: "+263712345678"

  // Profile Fields (go to user_information table)
  dateOfBirth?: string;
  gender?: string;
  country?: string;
  city?: string;
  streetAddress?: string;
  state?: string;
  zipCode?: string;

  // Document Fields (go to user_information table)
  documentType: 'nationalId' | 'passport';
  nationalIdNumber?: string;
  passportNumber?: string;

  // File Fields (go to user_information table)
  profilePictureUrl?: string; // Base64 or file path
  supportingDocuments?: any[]; // File objects before upload
}

// ═════════════════════════════════════════════════════════════════════════
// REQUEST/RESPONSE MODELS FOR BACKEND API
// ═════════════════════════════════════════════════════════════════════════

/**
 * RegistrationRequest - Data sent to backend
 * Endpoint: POST /auth/register (Auth Service)
 *
 * All required fields for creating a new user account
 */
export interface RegistrationRequest {
  referenceNumber?: string;
  firstName: string;
  surname: string;
  email: string;
  password: string;
  role: 'PATIENT' | 'DOCTOR' | 'ADMIN';
  mobilePhone: string;
  dateOfBirth?: string;
  gender?: string;
  country?: string;
  city?: string;
  nationalIdNumber?: string;
  passportNumber?: string;
}

/**
 * RegistrationResponse - Response from backend
 * After successful registration
 */
export interface RegistrationResponse {
  success: boolean;
  message: string;
  data?: {
    referenceNumber: string;
    email: string;
    role: string;
    id?: number;
  };
  error?: string;
}

/**
 * UserProfileUpdateRequest - Data sent to update user profile
 * Endpoint: PUT /users/{referenceNumber} (User Service)
 */
export interface UserProfileUpdateRequest {
  referenceNumber: string;
  dateOfBirth?: string;
  gender?: string;
  country?: string;
  city?: string;
  streetAddress?: string;
  state?: string;
  zipCode?: string;
  profilePictureUrl?: string;
  supportingDocuments?: string[];
  nationalIdNumber?: string;
  passportNumber?: string;
}

/**
 * UserProfileResponse - Response from backend profile update
 */
export interface UserProfileResponse {
  success: boolean;
  message: string;
  data?: UserInformation;
  error?: string;
}
